back:
    resource: "@BackBundle/Controller/"
    type:     annotation
    prefix:   /admin

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
